Strip redundant parentheses from assignment exprs
psf/black pull request #1906
Opened 2021-01-05 17:06 UTC by xrisk

This converts code of the form:

```
if (foo := 0):
    pass
```

into

```
if foo := 0::
    pass
```

which is consistent with how `if (foo):` is transformed into `if foo:` and also with examples in PEP 572. 

— 

Although all tests are passing, please review particularly this condition:
`and parent.children[1].type == token.EQUAL`

I am unsure if children[1] is always guaranteed to be operator.

2021-01-05 17:07 UTC, xrisk commented on src/black/__init__.py
> +        and parent.children[1].type == token.EQUAL
I’m not fully sure about this condition

2021-01-05 17:10 UTC, xrisk commented
Seems to break on pre-3.8. Will fix.

2021-01-05 19:21 UTC, xrisk commented
Alright fuzzer failures seem to be unrelated and they’re failing on HEAD as well.

2021-01-09 07:03 UTC, xrisk commented
@JelleZijlstra requesting a review!

2021-01-18 01:38 UTC, ichard26 commented
Reopening to re-run CI as the fuzz issues *should* be fixed.

2021-01-18 01:42 UTC, ichard26 commented
Okay we're hitting #1913 by chance now...

2021-01-18 05:34 UTC, xrisk commented
Hm the code I've touched seems unrelated to #1913. Do we wait for that to get resolved first?

2021-01-18 05:56 UTC, ichard26 commented
Sorry, should've made it clearer that the unrelated fuzz error was something we've seen before.  TR;DR: CI passed for your PR :tada:

2021-01-27 02:15 UTC, xrisk commented
Hi, please let me know if I need to do anything else here.

2021-02-16 20:47 UTC, ichard26 requested changes
Thanks for working on this! This is my first review of a formatting PR (I handle docs usually) so I hope I'm doing this right and carefully :) This should also be reviewed by Jelle since I believe they are our most qualified reviewer for this sort of stuff. But on with my review first!

Ideally this would have more test cases (complex if and while statements would be nice!), but it isn't a blocker.

> I am unsure if children[1] is always guaranteed to be the operator.

The answer is no :(

Here's a few examples of where `parent.children[1].type == token.EQUAL` falls apart:

1. `test += (a := 1)` (who would write this tho?)
2. `a, b = (test := (1, 2))`
3. `test: int = (test2 := 2)`

edit: don't ask me how to workaround this problem, I have no idea

Also, you'll need to edit [this section](https://github.com/psf/black/blob/master/docs/the_black_code_style.md#parentheses) adding a note how Black will not remove parentheses where an assignment expression is used since it's invalid.

2021-02-23 07:55 UTC, xrisk commented
Alright, I think it should be correct now. But perhaps we should wait for the refactoring that’s going on in #1958 to finish.

@jayaddison Are you planning to touch this code?

2021-02-23 11:48 UTC, jayaddison commented
@xrisk Thanks for checking; I'm not yet fully confident about the changes in #1958, so please don't consider it a blocker.

2021-02-27 22:40 UTC, ichard26 requested changes
> Also, you'll need to edit this section adding a note how Black will not remove parentheses where an assignment expression is used since it's invalid.

This was never resolved, please do so.

But overall, great improvement, thanks for your time and effort! If you please, add yourself to the AUTHORS list in the readme.

2021-02-27 22:42 UTC, ichard26 commented
> This is my first review of a formatting PR (I handle docs usually) so I hope I'm doing this right and carefully :) This should also be reviewed by Jelle since I believe they are our most qualified reviewer for this sort of stuff. But on with my review first

@JelleZijlstra, I would appreciate if you could make sure I haven't missed anything vital! This PR is mostly ready, just a few documentation issues (of which I can handle and review).

2021-02-28 01:20 UTC, JelleZijlstra approved these changes
Test cases look good and the change in black itself seems reasonable.

By the way, I'm the main person reviewing formatting changes in Black these days, but even I don't exactly feel like I know the codebase well.

2021-02-28 01:20 UTC, merged

2021-02-28 01:35 UTC, JelleZijlstra commented
Oops, I merged without resolving @ichard26's request about the documentation, sorry for that! @xrisk would you be able to send a followup PR? If not I can do it myself.

2021-02-28 01:39 UTC, ichard26 commented
> By the way, I'm the main person reviewing formatting changes in Black these days, but even I don't exactly feel like I know the codebase well.

You've got some experience at least compared to me :)

> Oops, I merged without resolving @ichard26's request about the documentation, sorry for that! @xrisk would you be able to send a followup PR? If not I can do it myself.

I was about to comment about that, don't fret too much as now I do see how you might have skipped over it since it was poorly worded. I should really reread stuff I write before pressing "comment". Ugh, old habits die hard.

2021-02-28 01:40 UTC, JelleZijlstra commented
@ichard26 don't blame yourself, it's my bad! You clearly requested changes, so I should have noticed.

2021-03-01 12:40 UTC, xrisk commented
@ichard26 

> Also, you'll need to edit this section adding a note how Black will not remove parentheses where an assignment expression is used since it's invalid.

Isn’t this implicit, since that section in the docs talks about “optional parentheses”? The parentheses as used in something like `x = (y := 5)` aren’t optional.

Also I would expect that behavior from the principle of least surprise, we should never be generating invalid code in the first place :P

2021-03-01 12:41 UTC, ichard26 commented
@xrisk yeah you're right lol. Apologies for the noise. Thanks for the PR!