add gedit integation fix
psf/black pull request #1962
Opened 2021-02-04 05:28 UTC by Architrixs

2021-02-05 01:03 UTC, ichard26 commented
pre-commit is still failing? also, I wanna give this a review soon.

2021-02-13 18:03 UTC, ichard26 requested changes
The bash script works just fine now, thanks!

Please address the failing prettier pre-commit hook once again and the style nits and this should be ready to go! Thanks again, if you want to, go add yourself to the AUTHORS list in the readme, you deserve it.

2021-02-13 18:03 UTC, ichard26 commented on docs/editor_integration.md
> +When you close and Reopen your File, black will be done with its job.
stylistic nits
```suggestion
When you close and reopen your File, _Black_ will be done with its job.
```

2021-02-14 06:43 UTC, Architrixs commented
pre-commit keeps failing here (even tho it passes on my ubuntu locally), so I'm gonna delete this branch and try from start and cloning again.

2021-02-14 06:43 UTC, closed without merging