Deprecate Python 2 formatting support
psf/black pull request #2523
Opened 2021-10-06 22:30 UTC by ichard26

### Description

It's 2021. See also #2251.

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2021-10-06 22:32 UTC, ichard26 commented
Just tagging this as a "do not merge" as all of this is very much up for debate.

2021-10-21 22:13 UTC, ichard26 commented
The current structure of the commits require that this is merged via a rebase so the split ends up being useful :)

> **Prepare for Python 2 depreciation** 
>
> - Use BlackRunner and .stdout in command line test
>
> So the next commit won't break this test. This is in its own commit so we can just revert the depreciation commit when dropping Python 2 support completely.

2021-10-30 18:46 UTC, cooperlees approved these changes
LGTM - Lets merge?

2021-10-30 18:57 UTC, graingert requested changes
The comments aren't consistent

2021-10-30 19:33 UTC, graingert approved these changes

2021-10-30 22:18 UTC, ichard26 commented
One potential problem I do want to bring up is that right now each call to format_str with Python 2 warns ... that may be too noisy.

2021-10-30 22:25 UTC, JelleZijlstra reviewed
Noticed one typo.

I'm also still thinking about the feature detection stuff here and brought it up on Discord.

2021-10-30 22:25 UTC, JelleZijlstra commented on docs/faq.md
> +this support will be dropped in the first stable release, expected for January 2022.
```suggestion
This support will be dropped in the first stable release, expected for January 2022.
```

2021-10-30 22:27 UTC, JelleZijlstra commented
Printing for each file might be noisy, but properly doing it only once might require communication across asyncio workers, which I don't really want to have to deal with.

2021-10-31 03:12 UTC, JelleZijlstra approved these changes
Let's merge it.

2021-10-31 14:58 UTC, aarav2you approved these changes

2021-10-31 23:46 UTC, merged