Declare support for Python 3.10
psf/black pull request #2562
Opened 2021-10-22 15:27 UTC by hugovk

### Description

Python 3.10 final is already tested, just needs the Trove classifier.

### Checklist - did you ...

- [ ] Add a CHANGELOG entry if necessary?
- [n/a] Add / update tests if necessary?
- [n/a] Add new / update outdated documentation?

Is a changelog entry needed?

---

By the way, Black was first released in March 2018 and took the forward-thinking view to only support Python 3.6, which was the newest release, and therefore Black hasn't needed to drop any EOL versions yet.

Python 3.6 is EOL on 2021-12-23; will Black be dropping 3.6 before the (potentially stable) 2022 Q1 release?

2021-11-09 19:05 UTC, kukushking commented
Hi folks, not quite sure this is the right place but shouldn't 3.10 be added to supported [target versions](https://github.com/psf/black/blob/b21c0c3d28d87bc944a1fdc979b30a0707b0df89/src/black/mode.py#L22) as part of this PR, too?

2021-11-09 19:08 UTC, jack1142 commented
Classifier just means that Black can run on Python 3.10, not that it can parse Python 3.10 code (which it currently can't when it comes to new syntax like match statement and parenthesized with) which is what would constitute to adding 3.10 target version.

2021-11-10 10:49 UTC, kukushking commented
Yep, I understand - just have no idea how are you handling 3.10 story so thought I'd mention it here in case you missed it.

2021-11-10 10:54 UTC, kukushking commented
Just found a [PR](https://github.com/psf/black/pull/2586) that has that covered. Thanks guys 🙌

2021-11-14 03:17 UTC, JelleZijlstra requested changes
Let's add this to the changelog

2021-11-14 09:52 UTC, hugovk commented
> Let's add this to the changelog

Added!

2021-11-14 14:03 UTC, JelleZijlstra commented on CHANGES.md
> +- Declare support for Python 3.10 (#2562)
```suggestion
- Declare support for Python 3.10 for running Black (#2562)
```

2021-11-14 14:37 UTC, merged