Standardize type comments
psf/black pull request #2698
Opened 2021-12-15 14:13 UTC by 13Ducks

### Description

Fixes #2097 and standardizes type comments to always have 1 space after the # and 1 space after the :

As per the issue, the functions `is_type_comment()` and `contains_pragma_comment()` have been modified to return true even with any extra spacing. Type comments without non-breaking spaces are now stripped of any extra spaces as well.

### Checklist - did you ...

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

^ Is documentation needed for this change? If so, I can add it.

2021-12-30 21:21 UTC, ichard26 commented
This was discussed on Python Discord but the summary of it is that we can't really normalize type comments until all of the major AST libraries that provide first-class type comment support are liberal in the whitespace they understand. It wouldn't be good to have a type comment that's ignored by typed-ast transformed into one that is noticed which then affects a type checker like mypy.

2022-01-27 02:03 UTC, JelleZijlstra requested changes
I don't remember the discussion @ichard26 alludes to above. Could you provide some details on how existing tools (typed-ast, pyright, pyre, ...) interpret spaces in type comments?

2022-01-27 02:20 UTC, ichard26 commented
Before I forget to link it again: https://discord.com/channels/267624335836053506/846434317021741086/921790074922864670

2022-02-03 16:12 UTC, CarliJoy commented on src/black/comments.py
> +        if re.match(r"#\s*(type\s*:|pylint\s*:|noqa\s*)", comment.value):
```suggestion
        if re.match(r"#\s*(type\s*:|pylint\s*:|noqa\s*|nosec\s*)", comment.value):
```
Would be nice if [Bandit](https://bandit.readthedocs.io/en/latest/config.html#suppressing-individual-lines) is supported as well.

2022-09-01 07:13 UTC, closed without merging

2022-09-02 11:43 UTC, CarliJoy commented
@13Ducks giving up on this MR ?