Document new Microsoft Black Formatter extension for VSCode
psf/black pull request #3063
Opened 2022-05-09 12:48 UTC by laundmo

### Description

VSCode announced a [new extension](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) for Black in their update notes for version 1.67.0, this PR adds a sentence to the editor integrations docs about this extension.

### Checklist - did you ...

- [ ] Add a CHANGELOG entry if necessary?
- [ ] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2022-05-09 16:17 UTC, cooperlees requested changes
Seems helpful for readers. Please just fix the lint.

2022-05-09 16:17 UTC, cooperlees commented on docs/integrations/editors.md
> +- Use the
Why was this indented? I think this is what is making linting upset.

2022-05-20 14:13 UTC, ichard26 approved these changes
The VSCode team is planning to remove the formatting integration with Black in the main Python extension eventually, but we can deal with that later when it happens :)

Nice to see you around @laundmo. Hope you've been doing well! Thank you for the PR!

2022-05-21 20:18 UTC, merged

2022-05-21 20:18 UTC, ichard26 commented
Congrats on your first PR to psf/black @laundmo! :tada: