[github action] display black result in job summary
psf/black pull request #3688
Opened 2023-05-13 15:48 UTC by tieum

### Description

This PR updates the black github action to display the output of black in the [job summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary)

### Checklist

- [x] Add an entry in `CHANGES.md` if necessary?
- [ ] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

### Result looks like this:
#### - erroring with verbosity on
<img width="871" alt="screenshot-2023-05-13-1727" src="https://github.com/psf/black/assets/814931/09fd636a-28f2-4786-ba5e-a62408239726">

#### - success with verbosity off
<img width="471" alt="screenshot-2023-05-13-1741" src="https://github.com/psf/black/assets/814931/f523c46c-e946-4826-90b3-cda84653cb7b">

2023-05-13 16:04 UTC, cooperlees requested changes
Just checking if we should care about the new lines, I feel it might mess up output people maybe parse and make things harder to read ...

2023-05-13 16:04 UTC, cooperlees commented on action/main.py
> +    sys.stderr.write("::error::Failed to install Black.")
Same as above

2023-05-13 16:23 UTC, tieum commented on action/main.py
> +        sys.stderr.write("::error::Failed to detect action version.")
It does need to be written to stderr so as errors do not appear in the job summary part (which won't parse it correctly) but the annotation one, like this:
<img width="472" alt="screenshot-2023-05-13-1815" src="https://github.com/psf/black/assets/814931/f41040a1-3a28-4c2f-b611-40bb5fcb31da">
I've updated the PR with your feedback

2023-05-14 13:12 UTC, tieum commented
I also checked action was correctly running on a Windows runner, an example run is here https://github.com/tieum/atuin-graph/actions/runs/4972553308

<img width="782" alt="screenshot-2023-05-14-1507" src="https://github.com/psf/black/assets/814931/e41df97b-04c1-4230-b7d9-90f6bc44f85e">
<img width="545" alt="screenshot-2023-05-14-1508" src="https://github.com/psf/black/assets/814931/fee6be39-3081-4fc0-81ee-a10e4894956d">

2023-05-14 15:25 UTC, cooperlees approved these changes
Thanks for taking my suggestions into account. This all looks good to me now to get the nicer summary and does the right thing to stderr output for all platforms :)

2023-05-15 21:35 UTC, merged