Avoid removing whitespace for walrus operators within subscripts
psf/black pull request #3823
Opened 2023-07-29 20:49 UTC by charliermarsh

### Description

At present, Black removes spaces around walrus operators within subscripts. For example, this is stable style:

```python
x[y:=1]
```

While rare in practice, it appears that this behavior is unintentional, and falls out from Black's removal of spaces around colons in slices (e.g., `x[y:z]`).

This PR removes that behavior, instead requiring spaces around walrus operators in such cases.

Closes https://github.com/psf/black/issues/3820.

### Checklist - did you ...

- [ ] Add an entry in `CHANGES.md` if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2023-07-29 20:51 UTC, charliermarsh commented
A related question -- Black's stable style uses:

```python
a[:(x := 13)]
```

Perhaps this should instead be:

```python
a[: (x := 13)]
```

(But I don't feel at all strongly here -- more asking if the stable style is intentional.)

2023-07-30 02:45 UTC, JelleZijlstra commented
> A related question -- Black's stable style uses:
> 
> ```python
> a[:(x := 13)]
> ```
> 
> Perhaps this should instead be:
> 
> ```python
> a[: (x := 13)]
> ```
> 
> (But I don't feel at all strongly here -- more asking if the stable style is intentional.)

I think the latter would be more consistent, since we add spaces to e.g. `'x[:a+4]'` and the walrus should generally be treated like any other operator.

2023-07-30 02:46 UTC, JelleZijlstra requested changes
This looks good, thanks! However, the change should be made only in the preview style: we'll promote it to stable in January.

2023-08-04 02:30 UTC, JelleZijlstra approved these changes

2023-08-04 02:34 UTC, hauntsaninja approved these changes
Thanks, this looks good! I made some minor changes to preview handling, tests and reformatted the source

2023-08-04 02:37 UTC, charliermarsh commented
Thanks!

2023-09-08 00:39 UTC, JelleZijlstra commented
Tests are failing on 3.8/3.9 because of a change noted in https://docs.python.org/3.10/whatsnew/3.10.html#other-language-changes: "Assignment expressions can now be used unparenthesized within set literals and set comprehensions, as well as in sequence indexes (but not slices)."

We should split out the offending tests into a separate test file that gets run only on 3.10+.

2023-09-08 14:37 UTC, merged