Add Black PyCharm 2023.2 integration instructions
psf/black pull request #3839
Opened 2023-08-15 15:21 UTC by jonashaag

I'm a bit uncreative as to what users might want to configure there

<img width="734" alt="image" src="https://github.com/psf/black/assets/175722/92fb5b57-a751-410d-9627-29b8ab04dfba">

### Description

### Checklist - did you ...

- [ ] Add an entry in `CHANGES.md` if necessary?
- [ ] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

2023-08-15 15:41 UTC, JelleZijlstra commented on docs/integrations/editors.md
>  There are three different ways you can use _Black_ from PyCharm:
```suggestion
There are several different ways you can use _Black_ from PyCharm:
```
Or "four", but what if number five comes along

2023-08-15 20:14 UTC, hauntsaninja requested changes

2023-08-15 21:03 UTC, jonashaag commented on docs/integrations/editors.md
>  startup cost on subsequent formats), but if you would prefer to not install a
How about this?

2023-09-08 00:34 UTC, JelleZijlstra approved these changes
Looks good (though I don't use PyCharm and haven't tried this).

@hauntsaninja are you OK with this PR now? (I can't merge since you requested changes.)

2023-09-08 01:35 UTC, hauntsaninja approved these changes
Looks reasonable to me (also do not use pycharm and haven't tried)

2023-09-08 01:35 UTC, merged