Update output display to job summary
psf/black pull request #3914
Opened 2023-10-02 13:51 UTC by csalerno-asml

### Description

Black default job summary isn't really readable, since Python code will be converted 1:1 in Markdown, leading to something like this: https://github.com/csalerno-asml/test-black-repo/actions/runs/6380983558#summary-17316480770 

### Checklist - did you ...

- [ ] Add an entry in `CHANGES.md` if necessary?
- [ ] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

2023-10-02 18:34 UTC, cooperlees requested changes
I like this idea. Makes a lot of sense.

I do wonder tho, can we break people who might be already parsing the output? If so, should we consider making a config parameter (if possible) to disable this code block new default?

2023-10-03 08:03 UTC, csalerno-asml commented
Hi @cooperlees , thanks for the feedback!

Regarding your concern, I am not really sure that somebody can/will parse the output?
I think the only use case with summaries is: an action/step write to `GITHUB_STEP_SUMMARY`, and a human read it via UI.

If a user wants to read the output of black, usually he/she will use `black` via CLI or with a pre-commit hook

2023-10-03 17:22 UTC, cooperlees approved these changes
Ok, I thought this was for human consumption only, was just checking we were not missing anything.

In that case lets add a change log entry so we show somewhere we've decided to make this change and rebase this and I'll merge.

Thankyou for your contribution!

2023-10-05 08:02 UTC, csalerno-asml commented
Hey @cooperlees , I noticed that the exit code was not handled correctly

2023-10-06 17:41 UTC, cooperlees commented
Many thanks again. This will help people see the changes to the code etc.

2023-10-06 17:41 UTC, merged

2023-10-19 15:18 UTC, heiner commented
I believe this change might have caused the GitHub action to fail without actionable output in some cases, e.g. in a way where the only output is:

```
Run psf/black@stable
  with:
    version: 23.10.0
    options: --check --diff
    src: .
    jupyter: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.18/x64
Run if [ "$RUNNER_OS" == "Windows" ]; then
  if [ "$RUNNER_OS" == "Windows" ]; then
    runner="python"
  else
    runner="python3"
  fi
  
  out=$(${runner} $GITHUB_ACTION_PATH/action/main.py)
  exit_code=$?
  
  # Display the raw output in the step
  echo "${out}"
  
  # Display the Markdown output in the job summary
  echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
  echo "${out}" >> $GITHUB_STEP_SUMMARY
  echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
  
  # Exit with the exit-code returned by Black
  exit ${exit_code}
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.18/x64
    INPUT_OPTIONS: --check --diff
    INPUT_SRC: .
    INPUT_JUPYTER: false
    INPUT_BLACK_ARGS: 
    INPUT_VERSION: 23.10.0
    pythonioencoding: utf-8
Error: Process completed with exit code 1.
```