fix: Remove parenthesis around sole list items
psf/black pull request #4312
Opened 2024-04-17 17:56 UTC by RedGuy12

Fixes #3545

### Description

I added this to the `hug_parens_with_braces_and_square_brackets` unstable style since there was a lot of overlapping code. I renamed it to `concise_nested_brackets` to reflect this. That is a breaking change if anyone was using `--enable-unstable-feature hug_parens_with_braces_and_square_brackets`, but to my knowlege, the existence of certain unstale features is not gurenteed to be stable. I can add the old name back as a (deprecated) alias or revert the rename altogether if so desired.

This *does* introduce more places where #4036 would be triggered:
```python
items = [  # type: ignore
    (  # type: ignore
        {"key1": "val1", "key2": "val2", "key3": "val3"}
        if some_var == "longstring"
        else { "key": "val" }
    )
]
```
I'll try to tackle that in a seperate PR.

### Checklist - did you ...

- [n] Add an entry in `CHANGES.md` if necessary?
- [y] Add / update tests if necessary?
- [y] Add new / update outdated documentation?

2024-04-24 03:02 UTC, JelleZijlstra commented on docs/the_black_code_style/future_style.md
> +Parenthesises around sole list items will also be removed for similar reasons. Trailing
```suggestion
Parentheses around sole list items will also be removed for similar reasons. Trailing
```

2024-04-24 03:09 UTC, JelleZijlstra requested changes
Thanks, these changes look good.

However, I think I'd prefer to keep feature names stable through the year. The main motivation for adding `--enable-unstable-feature` was to allow users who want to keep some feature on to just turn on the feature in their config and have it keep working.

Also, I don't want to accept a PR that directly adds a new unstable style. I see the unstable style as a holding pen for style changes that we'd originally put into preview but later ran into issues with. New style features should go into preview instead.

2024-06-07 21:11 UTC, RedGuy12 commented
Apologies for the delay @JelleZijlstra, I've had other priorities recently.

The main issue was `hug_parens_with_braces_and_square_brackets` was required for the parens to be removed around multi-line expressions. I tried to identify exactly what parts it depended on, but I don't think it would be an easy refactor. I settled on just documenting this limitation instead.

I put `remove_lone_list_item_parens` in the unstable style due to this limitation, although it does work on its own for simple cases. If desired, I could move it to the preview style so preview users could get the benefits in those cases, or we could wait for `hug_parens_with_braces_and_square_brackets`. The original issue #3545 was for the more complex cases.

2024-10-06 01:18 UTC, cobaltt7 commented
Hey @JelleZijlstra just returned to this PR, sorry for letting it go stale

I removed this change from the unstable style, because it doesn't add any issues on its own, it just doesn't work in all cases without `hug_parens_with_braces_and_square_brackets`. I also resolved the conflicts.

Do these changes look good?

2024-10-08 05:56 UTC, JelleZijlstra reviewed
Thank you!

2024-10-08 05:56 UTC, JelleZijlstra commented on CHANGES.md
> +- Remove parenthesis around sole list items (#4312)
```suggestion
- Remove parentheses around sole list items (#4312)
```

2024-10-08 05:56 UTC, JelleZijlstra commented on tests/data/cases/preview_remove_lone_list_item_parens.py
> +items = [(123)]
Add a test containing a generator expression, to make sure we don't turn it into a listcomp:

```
>>> [(x for x in [1])]
[<generator object <genexpr> at 0x104277400>]
>>> [x for x in [1]]
[1]
```

Also add tests with comments in various places (e.g., after the opening paren, before the closing paren). Such cases tend to expose bugs in Black.

2024-11-26 04:24 UTC, JelleZijlstra approved these changes

2024-11-26 04:24 UTC, JelleZijlstra commented
Maybe we should also extend this to single-element sets? The code should be very similar.

2024-11-27 23:44 UTC, cobaltt7 commented
@JelleZijlstra Done!

2024-11-28 03:59 UTC, JelleZijlstra approved these changes

2024-11-28 03:59 UTC, merged