fix: fix PEP 646 support of tuple unpacking
psf/black pull request #4440
Opened 2024-08-22 06:25 UTC by terencehonles

### Description

This change fixes unpacking a tuple or generic type when *args is a type variable tuple.

### Checklist - did you ...

- [ ] Add an entry in `CHANGES.md` if necessary?
- [x] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

2024-08-22 13:26 UTC, JelleZijlstra requested changes
Thanks, this is a good catch. However, as it is a change in style, it should be applied only to Black's preview style.

2024-08-22 14:15 UTC, terencehonles commented
> Thanks, this is a good catch. However, as it is a change in style, it should be applied only to Black's preview style.

Guidance on that probably would have been useful, but I believe I may have figured it out

2024-08-22 15:23 UTC, JelleZijlstra approved these changes
Thanks!

2024-08-22 16:25 UTC, JelleZijlstra commented on CHANGES.md
> +  fn(*args: *tuple[*Ts, T]) -> None: pass`)
```suggestion
  fn(*args: *tuple[*Ts, T]) -> None: pass`) (#4440)
```

2024-08-22 16:26 UTC, JelleZijlstra commented
There's a CI failure that looks unrelated to your change, probably due to a typing change in a dependency. I can look into it over the next few days.

2024-08-22 20:55 UTC, terencehonles commented on CHANGES.md
> +  fn(*args: *tuple[*Ts, T]) -> None: pass`)
done

2024-08-25 13:16 UTC, terencehonles commented
> There's a CI failure that looks unrelated to your change, probably due to a typing change in a dependency. I can look into it over the next few days.

I fixed the last lint error by updating the schema

2024-08-26 15:09 UTC, merged

2024-08-26 15:10 UTC, JelleZijlstra commented
Thank you!